import { Inter, Titillium_Web } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const titilum = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "600", "400", "900", "700"],
  variable: "--font-titi",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${titilum.variable}`}>
        {children}
      </body>
    </html>
  );
}
